# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 09:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardnumber', models.BigIntegerField(blank=True)),
                ('expiry_month', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('expiry_year', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('cvv', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('card_type', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=1000)),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('detail', models.CharField(blank=True, max_length=1000)),
                ('redeem', models.CharField(blank=True, max_length=1000)),
                ('percent', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_id', models.CharField(blank=True, max_length=12)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('item', models.CharField(blank=True, max_length=1000)),
                ('reward', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('treward', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
