# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 06:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tr_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry_month',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry_year',
            field=models.IntegerField(blank=True),
        ),
    ]
