# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-25 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20170925_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cardnumber',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry_month',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry_year',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
