# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_auto_20170925_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
    ]
