DB_NAME = ''
DB_USER = ''
DB_PASSWORD = ''

SOCIAL_AUTH_FACEBOOK_KEY = ''
SOCIAL_AUTH_FACEBOOK_SECRET = ''



SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = ''

SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = ''

EMAIL_HOST_USER = 'giri492neeraj@gmail.com'
EMAIL_HOST_PASSWORD = '8960377614'